language: node_js
node_js:
    - 11
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: public
    on:
        branch: master

env:
    global:
        secure: mlPws6DiRf4rwOcFc5mqS1Ku9fN8oibk37815Ibu4XcmMf8rySRsG9HXG4lWQeoDUO3mP0HRa3J1ndHCz6bMuku/f+9OvB9NyPad+eFugFqGwoyGr+VqGpxfJCjZg3PVL6CjBCdFbn8FiJ434B3yiiOwiq4xAmyKYJU7XoH67xAT2wlXHokf0RweDOapCvWYGki8xI7pTEH8F0Ks+f2GZRxm+BijvvJgtM48OClqeVqWrHS1G3CS0cjWfFKO/XvzU4uYkkn0CBvPunEpobAEXVpfxiJRGeHHBfrBhrPVqu56mRipU7Pma9N3HNeEaTxsqDzwMPjWzUe4cAlG4z4AUGXE1sb5MsCymGwRGMa+bHmiIBn1KiisRbjWb2xgCzN0HPghi9ZejT5KebOxz3QKqGsacWsn91pXXEQ4o5PPucBnz0naA3Ht/CrTwougq7Og2u+XRf761JkhsGS6Hpr14jiF1Gic+RC2ArMvml+BKRqLf9UdLPBHUIKVqbqAcRpQSM+xmkakt0qF1ulGIdu1kgugIl/He8jSOItSlAAzdKGfVSKi3u5VgHdEGx9uYbkX1F1WjJrxCfsypoYKYr4Kek2zIwwh6DLnjfJ117rrbQC4hUn5u2l2A1nPmdrSCcCee644T7L7OBKn2Vsso2+Yaqe46WYCh0BYeBMHI9GBV8Y=
